import { mkdir, readFile, readdir, copyFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const webRoot = resolve(scriptDir, "..");
const projectRoot = resolve(webRoot, "..");
const dataRoot = join(projectRoot, "data");
const sourceAssetRoot = join(projectRoot, "site", "assets", "stories");
const publicAssetRoot = join(webRoot, "public", "assets", "stories");
const generatedPath = join(webRoot, "src", "data", "generated-content.ts");

async function readJson(name) {
  const value = await readFile(join(dataRoot, `${name}.json`), "utf8");
  return JSON.parse(value);
}

function toConstExport(name, value, typeName) {
  return `export const ${name} = ${JSON.stringify(value, null, 2)} satisfies ${typeName}[];\n`;
}

async function copyStoryAssets() {
  await mkdir(publicAssetRoot, { recursive: true });
  let files = [];
  try {
    files = await readdir(sourceAssetRoot);
  } catch {
    return 0;
  }

  let copied = 0;
  for (const file of files) {
    if (!/\.(png|jpe?g|webp|gif|svg)$/i.test(file)) continue;
    await copyFile(join(sourceAssetRoot, file), join(publicAssetRoot, file));
    copied += 1;
  }
  return copied;
}

const [reporters, stories, sourceItems, evergreenGuides] = await Promise.all([
  readJson("reporters"),
  readJson("stories"),
  readJson("source-items"),
  readJson("evergreen-guides"),
]);

const generated = [
  "import type { EvergreenGuide, Reporter, SourceItem, Story } from \"@/lib/types\";",
  "",
  "// Generated by `npm run ingest`. Edit root data/*.json, then rerun ingestion.",
  toConstExport("reporters", reporters, "Reporter"),
  toConstExport("stories", stories, "Story"),
  toConstExport("sourceItems", sourceItems, "SourceItem"),
  toConstExport("evergreenGuides", evergreenGuides, "EvergreenGuide"),
].join("\n");

await mkdir(dirname(generatedPath), { recursive: true });
await writeFile(generatedPath, generated, "utf8");
const assetCount = await copyStoryAssets();

console.log(
  `Ingested ${stories.length} stories, ${sourceItems.length} source items, ${evergreenGuides.length} evergreen guides, and ${assetCount} story assets.`,
);
